- name: This sets up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ubuntu
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/aws-pem-file"  
    ansible_ssh_user: "ubuntu"

  tasks:
  - name: "update apt repository cache"
    apt:
      update_cache: yes

  - name: "Install apache2 and php packages"
    apt:
        name:
          - "apache2"
          - "php"
        state: present

  - name: "copy code to dest"
    get_url:
        url: https://devopscube.com/
        dest: "/var/www/html/index.php"

  - name: "Start and enable apache2 service"
    service:
        name: apache2
        state: started
        enabled: yes

  - name: "Install additional packages"
    apt:
      name:
        - wget
        - unzip
      state: latest  
      
  - name: "Install terraform"
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
